{"metadata":{"kernelspec":{"display_name":"Python (Pyodide)","language":"python","name":"python"},"language_info":{"codemirror_mode":{"name":"python","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8"}},"nbformat_minor":5,"nbformat":4,"cells":[{"id":"02a0e2ac-452b-4c2d-8d96-4a4d74777533","cell_type":"markdown","source":"# Iterated function system\n\nYou draw triangles, the code draws fractal image.\n\n* Ctrl + Left Click: add a new point\n* Backspace: remove the last point\n* Left Drag and Drop: move a point\n* Shift + Left Click: start moving all points, click again to finish the move","metadata":{},"attachments":{}},{"id":"b985e187-4617-4936-8d06-8a9d771868f8","cell_type":"code","source":"import cffi\nimport ipywidgets\nimport ipycanvas\nimport ipyevents\nimport matplotlib","metadata":{"trusted":true},"outputs":[],"execution_count":1},{"id":"46d5fa59-58d4-44b0-a894-7289e5b32d89","cell_type":"code","source":"from ifs import IFS\n\ngui = IFS()\ngui.layout","metadata":{"trusted":true},"outputs":[{"execution_count":2,"output_type":"execute_result","data":{"text/plain":"VBox(children=(HBox(children=(Dropdown(layout=Layout(width='120px'), options=('光芒四射', '蕨类植物', '旋涡', '隧道', '杂草'…","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"dd20129670b14b5eb069314f6dbf9934"}},"metadata":{}},{"name":"stderr","output_type":"stream","text":"Exception in callback WebLoop._decrement_in_progress(<PyodideTask ...s/ifs.py:286>>)\nhandle: <Handle WebLoop._decrement_in_progress(<PyodideTask ...s/ifs.py:286>>)>\nTraceback (most recent call last):\n\n  File \"/lib/python312.zip/asyncio/events.py\", line 88, in _run\n    self._context.run(self._callback, *self._args)\n\n  File \"/lib/python312.zip/pyodide/webloop.py\", line 362, in _decrement_in_progress\n    and (exc := fut.exception())\n                ^^^^^^^^^^^^^^^\n\n  File \"/drive/plots/ifs.py\", line 286, in timer_task\n    async def timer_task(self):\n\nasyncio.exceptions.CancelledError\n\nException in callback WebLoop._decrement_in_progress(<PyodideTask ...s/ifs.py:286>>)\nhandle: <Handle WebLoop._decrement_in_progress(<PyodideTask ...s/ifs.py:286>>)>\nTraceback (most recent call last):\n\n  File \"/lib/python312.zip/asyncio/events.py\", line 88, in _run\n    self._context.run(self._callback, *self._args)\n\n  File \"/lib/python312.zip/pyodide/webloop.py\", line 362, in _decrement_in_progress\n    and (exc := fut.exception())\n                ^^^^^^^^^^^^^^^\n\n  File \"/drive/plots/ifs.py\", line 286, in timer_task\n    async def timer_task(self):\n\nasyncio.exceptions.CancelledError\n\n"}],"execution_count":2},{"id":"e0d12c94-ce3b-4086-a5e2-452187456a9d","cell_type":"code","source":"","metadata":{"trusted":true},"outputs":[],"execution_count":null}]}